---
title: One Variable Linear Equations
draft: TRUE
---

#Analyzing the number of solutions to linear equations.

$$3\left(y + 9\right) = 12y + 13$$

We'll manipulate the equation in order to simplify it and isolate $y$. We should end with one of the following cases:

* An equation of the form $y = a$ (where $a$ is any number). In this case, the equation has exacly one solution.

* An equation in the form $a = a$ (where $a$ is any number). In this case the equation has infinite solutions.

* An equation of the form $a = b$ (where $a$ and $b$ are different numbers). In this case, the equation has no solutions. 

**Simplifying the equation**

$$3\left(y + 9\right) = 12y + 13$$
$$3y + 27 = 12y + 13$$
$$\left(3y - 12y\right) = \left(13 - 27\right)$$
$$-9y = -14$$
$$y = -\frac{14}{9}$$

So, in this instance because $y = a$ we have exactly one solution.

From [KhanAcademy.org](https://www.khanacademy.org/math/algebra/one-variable-linear-equations/alg1-number-of-solutions-to-linear-equations/e/solutions-to-linear-equations):

> It's helpful to think about our equation graphically. 

> Both the left hand side and the right hand side of our equation represents a line. So when we set the two sides equal to each other and simplify the equation, we are looking for any points that the two lines might share. 

> Therefore, any solutions to our equation represent the number of points that the lines share.

> * If the two lines are different, but not parallel, they intersect at exactly one point. This corresponds to ending up with an equation of the form $y = a$.

> * If the two lines are the same, then they share all of their points (and there are infinitely many such points). This corresponds to ending up with an equation of the form $a = a$.

> * If the two lines are different and parallel, they share no points. This corresponds to ending up with a false equation of the form $a = b$, where $a$ and $b$ are different numbers.

**How many solutions does the following equation have?**

$$6\left(x + 7\right) = -4x - 2$$
$$6x + 42 = -4x - 2$$
$$\left(6x + 4x\right) = \left(-2 - 42\right)$$
$$10x = -44$$
$$x = -\frac{44}{10}$$

Because $x = a$ the equation above has exactly one solution.

**How many solutions does the following equation have?**

$$74y - 8 - 78y = -4y - 8$$
$$74y - 78y + 4y = -8 + 8$$
$$0  = 0$$

Here, because $a = a$ there are infinitely many solutions.

**How many solutions does the following equation have?**

$$3z + 9 + 14z = 4z + 5$$
$$3z + 14z - 4z = 5 - 9$$
$$13z = -4$$
$$z = -\frac{4}{13}$$

This equation has exactly one solution.

---

###Complete missing values in linear equations according to the number of solutions

**Which values of $P$ and $Q$ result in an equation with exactly one solution?**

$$Px + 50 = -2x + Q$$

From [KhanAcademy.org](https://www.khanacademy.org/math/algebra/one-variable-linear-equations/alg1-number-of-solutions-to-linear-equations/e/complete-equations-according-to-solutions):

An equation of the form $ax + b = cx + d$ has:

* exactly one solution when $a \neq c$, 
* no solutions when $a = c$ and $b \neq d$, and 
* infinitely many solutions when $a = c$ and $b = d$

Let's rewrite the given equation in this form to find the correct values for $P$ and $Q$.

####Finding the correct values of $P$ and $Q$

When we rewrite $Px + 50 = -2x + Q$ in the form $ax + b = cx + d$, we see that $a = P$, $b = 50$, $c = -2$, and $d = Q$.

In order for our given equation to ahve exactly one solution, $a$ must be different from $c$. In other words, $P$ must be different from $-2$.

The only options that satisfy this are given below:

* $P = 2$ and $Q = -2$
* $P = 50$ and $Q = 50$

**Which values of $P$ and $Q$ result in an equation with no solutions?**

$$Qx + P = 33x + 25$$

In this equation, we are looking for results that have *no solutions*, therefore we need to find where $a = c$ and $b \neq d$. 

Our options are:
1. $Q = 33$ and $P = 25$
2. $Q = 33$ and $P = -25$
3. $Q = 33$ and $P = -33$
4. $Q = 33$ and $P = 33$

In the equation, $c = 33$ so $a$ or $Q$ have to equal 33. That doesn't rule out any of the options because all of which have $Q = 33$.

We also know $b \neq d$. In the equation, $b = P$ and $d = 25$. So $P$ *cannot* equal $25$. Option 1 has $P = 25$ but the other options do not. Therefore our answer would be options 2, 3 and 4.

**Which values of $P$ and $Q$ result in an equation with *no solutions*?**

$$29x + P = Qx - 11$

Options:
1. $P = 29$ and $Q = 29$
2. $P = 92$ and $Q = 29$
3. $P = 11$ and $Q = 29$
4. $P = -29$ and $Q = 29$

Again, here we are looking for the options that give *no solutions* so $a = c$ and $b \neq d$. 

In our equation, $Q = 29$ which is present in all of the options. Next, we identify $d = -11$, therefore, $P \neq -11$. That option is not available above. 

Therefore, all options result in the equation having no solutions.

**Which values of $P$ and $Q$ result in an equation with *no solutions*?**

$$Px + 5 = -4x + Q$$

Options:
1. $P = -4$ and $Q = -5$
2. $P = 4$ and $Q = 5$
3. $P = -4$ and $Q = -4$
4. $P = 5$ and $Q = -5$

*No solutions*, so $a = c$ or $P = -4$ and $b \neq d$ or $5 \neq Q$. Options 2 and 4 are eliminated because $P \neq 4$. Option 2 is also eliminated because $Q \neq 5$. Options 1 and 3 remain valid options.

**Which values of $P$ and $Q$ result in an equation with *infinitely many solutions*?**

$$Px + Q = 46x + 23$$

In this example, we want *infinitely many solutions*, therefore, we need options where $a = c$ **and** $b = d$. Therefore, $P = 46$ and $Q = 23$.

Options:

1. $P = 46$ and $Q = -23$
2. $P = -46$ and $Q = -23$
3. $P = 46$ and $Q = -23$
4. $P = 46$ and $Q = 23$

The only options that satisfy our criteria is option 4, $P = 46$ and $Q = 23$. 

Option 1 is disqualified because $Q \neq -23$. Option 2 is disqualified because $P \neq -46$. And, option 3 is disqualified, again, because $Q \neq -23$. 

