---
title: Units of Measure in Modeling
draft: TRUE
---

## Introduction to Dimensional Analysis

[KhanAcademy.org](https://www.khanacademy.org/math/algebra/units-in-modeling/intro-to-dimensional-analysis/v/dimensional-analysis-units-algebraically)

$$d = rt$$

Treat $d$, $r$, and $t$ like variables.

$$r = 5\frac{m}{s}$$

$$t = 10s$$

$$d = \left(5\frac{m}{s}\right)(10s)$$

$$d = (5)(10)*\left(\frac{m}{s}\right)(s)$$

$$d = (5*10)\left(\frac{m}{s}*s\right)$$

$$d = 50m$$

---
$$r = 5\frac{m}{s}$$

$$t = 1h$$

$$d = \left(5\frac{m}{s}\right)(t)$$

$$d = \left(5\frac{m}{s}\right){1h}$$

$$d = (5*1)\left(\frac{m}{s}*h\right)$$

$$d = 5\left(\frac{mh}{s}\right)$$

Convert $h$ to $s$:

$$h = 60 * 60 = 3600$$

$$d = 5 * m * \left(\frac{3600}{1}\right)$$

$$d = 3600 * 5 * m$$

$$d = 18,000m$$

Convert $m$ to $km$:

$$d = (18,000m)\left(\frac{km}{m}\right)$$
$$d = (18,000m)\left(\frac{1km}{1000m}\right)$$
$$d = \frac{18,000km}{1,000m}$$
$$d = 18km$$

###How to determine the appropriate unit of a quantity given a formula containing that quantity

$$K = \frac{b}{s^2}$$

$b$ is  centimeters ($cm$)

$s$ is grams/centimeter or $\frac{g}{cm}$

$$K = \frac{cm}{\frac{g}{cm}^2}$$

$b = 1cm$ and $s = 1\frac{g}{cm}$

$$K = \frac{1cm}{\frac{1g}{cm}^2}$$

$$K = \frac{1cm}{1\frac{g^2}{cm^2}}$$

$$K = 1cm * \frac{1}{1} * \frac{cm^2}{g^2}$$

$$K = \frac{cm^3}{g^2}$$

####Example

Consider the formual $B = \frac{F}{qv}$ where:

* $B$ represents magnetic field, 
* $F$ represents force and has units of Newtons ($N$), 
* $q$ represents charge and has units of coulombs ($C$), and 
* $v$ represents velocity and has units of meters per second $\left(\frac{m}{s}\right)$

Select an appropriate measurement unit for magnetic field:
1. $$\frac{N*C}{s*m}$$
2. $$\frac{N*s}{C*m}$$
3. $$\frac{N*m}{C*s}$$
4. $$\frac{C*m}{N*s}$$

So, $B = \frac{F}{qv}$ can be rewritten as:
$$B = \frac{N}{C\frac{m}{s}}$$

I'll clean up the denominator first.

$$B = \frac{N}{\frac{C*m}{s}}$$

$$B = N * \frac{s}{C*m}$$

$$B = \frac{N * s}{C * m}$$

Therefore, option 2 is correct.

####Example

Consider the formula $K = \frac{1}{2}mv^2$, where
* $K$ represents kinetic energy, 
* $m$ represents mass and has units of kilograms ($kg$), and 
* $v$ represents velocity and has units of meters per second $\left(\frac{m}{s}\right)$

Options are:
1. $$kg^2 * m^2 * s^2$$
2. $$\frac{kg*m}{s^2}$$
3. $$\frac{kg*m^2}{s^2}$$
4. $$\frac{kg^2*m^2}{s^2}$$

I'll rewrite the equation[^footnote]:

[^footnote]: [KhanAcademy notes:](https://www.khanacademy.org/math/algebra/units-in-modeling/intro-to-dimensional-analysis/e/working-with-units)  
> The constant term int he formula, $\frac{1}{2}$, does not affect the units of any of the varaible terms.

$$K = kg\left(\frac{m}{s}\right)^2$$
$$K = \frac{kg*m^2}{s^2}$$

Therefore, option 3 above is correct.

####Example

Consider the formula $F = ma$, where
* $F$ represents force, 
* $m$ represents mass and has units of kilograms($kg$), and 
* $a$ represents acceleration and has units of meters per second squared $\left(\frac{m}{s^2}\right)$

Select an appropriate measurement unit for force:
1. $$\frac{kg^2 * m}{s^2}$$
2. $$\frac{kg * m^2}{s^2}$$
3. $$\frac{kg * m}{s^2}$$
4. $$\frac{kg * m^2}{s}$$

Solve:

$$F = (kg)\left(\frac{m}{s^2}\right)$$
$$F = \frac{kg * m}{s^2}$$

Option 3 is correct. 

###Solve word problems with multiple units

####Example
Bernice sells 135 sea shells by the sea shore every day. She sells each sea shell for $3. 

For how many days does Bernice need to sell sea shells to earn $2,430?

$$x = \$135* 3$$
$$d = \frac{\$2,430}{x}$$
$$d = \frac{\$2,430}{\$405}$$
$$d = 6$$

####Example
Each of Hashim's comedy shows lasts for 75 minutes. He tells an average of 8 jokes every minute.

How many of Hashim's comedy shows does one need to watch to hear 2400 jokes?

$s$ equals 75 minutes or $75m$. $j$ equals jokes per minute.  And, $t$ is the total number of jokes or 2400. $x$ will be our solution.

$$x = \frac{t}{js}$$
$$x = \frac{2400}{(8)(75)}$$
$$x = \frac{2400}{600} = \frac{24}{6} = 4$$
