version: '3.4'

services:

  rstudio:
    image: timtrice/web:latest
    container_name: web_rstudio
    restart: "no"
    volumes:
      - /home/timtrice/Projects/.Renviron:/home/rstudio/.Renviron
      - /home/timtrice/Projects/web:/home/rstudio/web
    ports:
      - "8787:8787"

#  jupyter:
#    image: jupyter/datascience-notebook:92fe05d1e7e5
#    container_name: web_jupyter
#    restart: "no"
#    command: start-notebook.sh --NotebookApp.password=sha1:13a4808aa90c:dbeb882e4fdc7b067a50c4dc53bba7ff7a6b7a40
#    volumes:
#      - /home/timtrice/Projects/web:/home/jovyan/web
#    ports:
#      - "8888:8888"

networks:
  default:
    external:
      name: databases

