version: '3.1'

services:

  mariadb:
    image: mariadb:10.3.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qNlr0rZtf5VfGQ9m
    volumes:
      - web_mariadb:/var/lib/mysql

  postgres:
    image: postgres:9.6.5
    restart: always
    environment:
      POSTGRES_PASSWORD: 5aJhjS7g7SAzE56K
    volumes:
      - web_postgres:/var/lib/postgresql/data

  web:
    image: timtrice/web
#    Running the command below works and the notebook will run but RStudio will
#    not load for some reason.
#    command: jupyter-notebook --ip="*" --no-browser --allow-root
    volumes:
      - .:/home/rstudio/web
      - ../.Renviron:/home/rstudio/.Renviron
    ports:
      - "8787:8787"
      - "8888:8888"
    depends_on:
      - mariadb
      - postgres

volumes:
  web_mariadb:
    external: true
  web_postgres:
    external: true

