version: '2.0'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  jupyter:
    image: timtrice/web:jupyter # docker pull jupyter/datascience-notebook
    restart: always
    command: start-notebook.sh --NotebookApp.password=sha1:13a4808aa90c:dbeb882e4fdc7b067a50c4dc53bba7ff7a6b7a40
    volumes:
      - ~/Projects/web:/home/jovyan/web
    ports:
      - "8888:8888"
    depends_on:
      - mariadb
      - mysql
      - postgres

  mariadb:
    image: timtrice/web:mariadb # mariadb:10.3.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qNlr0rZtf5VfGQ9m
    volumes:
      - ~/Projects/data/mariadb:/var/lib/mysql

  mysql:
    image: timtrice/web:mysql # mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: e99rntuUXMGHB6Zt
    volumes:
      - ~/Projects/data/mysql:/var/lib/mysql

  # As is, does not work through adminer. Shows port 5432 as not being open. 
  postgres:
    image: timtrice/web:postgres # postgres:9.6.5
    restart: always
    environment:
      POSTGRES_PASSWORD: 5aJhjS7g7SAzE56K
    volumes:
      - ~/Projects/data/postgres:/var/lib/postgresql/data

  rstudio:
    image: timtrice/web:rstudio # rocker/rstudio:3.4.2
    restart: always
    volumes:
      - ~/Projects/web:/home/rstudio/web
      - ~/Projects/.Renviron:/home/rstudio/.Renviron
    ports:
      - "8787:8787"
    depends_on:
      - mariadb
      - mysql
      - postgres

