version: '3.1'

services:

  mariadb:
    image: timtrice/andromeda
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qNlr0rZtf5VfGQ9m
    networks:
      mynet:
        ipv4_address: 172.25.0.10

  postgres:
    image: timtrice/antila
    restart: always
    environment:
      POSTGRES_PASSWORD: 5aJhjS7g7SAzE56K
    networks:
      mynet:
        ipv4_address: 172.25.0.20

  web:
    image: timtrice/web
#    Running the command below works and the notebook will run but RStudio will
#    not load for some reason.
#    command: jupyter-notebook --ip="*" --no-browser --allow-root
    volumes:
      - .:/home/rstudio/web
      - ../.Renviron:/home/rstudio/.Renviron
    ports:
      - "8787:8787"
      - "8888:8888"
    depends_on:
      - mariadb
      - postgres

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
