<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="theme" content="hugo-academic">
  <meta name="generator" content="Hugo 0.30.2" />
  <meta name="author" content="Tim Trice">

  
  
  
  
    
      
    
  
  <meta name="description" content="Test abstract
">

  
  <link rel="alternate" hreflang="en-us" href="../../r/beer-reviews-analysis/">

  


  

  
  
  <meta name="theme-color" content="#795548">
  
  
  
  
    
  
  
    
    
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css">
    
  
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha512-6MXa8B6uaO18Hid6blRMetEIoPqHf7Ux1tnyIQdpt9qI5OACx7C+O3IVTr98vwGnlcg0LOLa02i9Y1HpVhlfiw==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.1/css/academicons.min.css" integrity="sha512-NThgw3XKQ1absAahW6to7Ey42uycrVvfNfyjqcFNgCmOCQ5AR4AO0SiXrN+8ZtYeappp56lk1WtvjVmEa+VR6A==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">
  
  
  
  
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700%7cRoboto:400,400italic,700%7cRoboto&#43;Mono">
  
  <link rel="stylesheet" href="../../styles.css">
  

  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-1507390-26', 'auto');
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="//www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  

  
  <link rel="alternate" href="../../index.xml" type="application/rss+xml" title="Tim Trice">
  <link rel="feed" href="../../index.xml" type="application/rss+xml" title="Tim Trice">
  

  <link rel="manifest" href="../../site.webmanifest">
  <link rel="icon" type="image/png" href="../../img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="../../img/icon-192.png">

  <link rel="canonical" href="../../r/beer-reviews-analysis/">

  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@https://twitter.com/timtrice">
  <meta property="twitter:creator" content="@https://twitter.com/timtrice">
  
  <meta property="og:site_name" content="Tim Trice">
  <meta property="og:url" content="/r/beer-reviews-analysis/">
  <meta property="og:title" content="Analysis of Beer Reviews | Tim Trice">
  <meta property="og:description" content="Test abstract
">
  <meta property="og:locale" content="en-us">
  
  
  
  

  

  <title>Analysis of Beer Reviews | Tim Trice</title>

</head>
<body id="top" data-spy="scroll" data-target="#toc" data-offset="71" >

<nav class="navbar navbar-default navbar-fixed-top" id="navbar-main">
  <div class="container">

    
    <div class="navbar-header">
      
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a class="navbar-brand" href="../../">Tim Trice</a>
    </div>

    
    <div class="collapse navbar-collapse">

      
      
      <ul class="nav navbar-nav navbar-right">
        

        
        
        
        
        
          
        

        <li class="nav-item">
          <a href="../../#publications_selected">
            
            <span>Publications</span>
            
          </a>
        </li>

        
        

        
        
        
        
        
          
        

        <li class="nav-item">
          <a href="../../#posts">
            
            <span>Posts</span>
            
          </a>
        </li>

        
        

        
        
        
        
        
          
        

        <li class="nav-item">
          <a href="../../#projects">
            
            <span>Projects</span>
            
          </a>
        </li>

        
        

        
        
        
        
        
          
        

        <li class="nav-item">
          <a href="../../#contact">
            
            <span>Contact</span>
            
          </a>
        </li>

        
        

        
        
        
        
        
          
        

        <li class="nav-item">
          <a href="../../#about">
            
            <span>About</span>
            
          </a>
        </li>

        
        
      

      
      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  


  <div class="article-container">
    <h1 itemprop="name">Analysis of Beer Reviews</h1>

    

<div class="article-metadata">

  <span class="article-date">
    
        Last updated on
    
    <time datetime="0001-01-01 00:00:00 &#43;0000 UTC" itemprop="datePublished dateModified">
      Jan 1, 0001
    </time>
  </span>
  <span itemscope itemprop="author publisher" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Tim Trice">
  </span>

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    15 min read
  </span>
  

  
  
  <span class="middot-divider"></span>
  <a href="../../r/beer-reviews-analysis/#disqus_thread"></a>
  

  

  
  
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=Analysis%20of%20Beer%20Reviews&amp;url=%2fr%2fbeer-reviews-analysis%2f"
         target="_blank" rel="noopener">
        <i class="fa fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fr%2fbeer-reviews-analysis%2f"
         target="_blank" rel="noopener">
        <i class="fa fa-facebook"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fr%2fbeer-reviews-analysis%2f&amp;title=Analysis%20of%20Beer%20Reviews"
         target="_blank" rel="noopener">
        <i class="fa fa-linkedin"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fr%2fbeer-reviews-analysis%2f&amp;title=Analysis%20of%20Beer%20Reviews"
         target="_blank" rel="noopener">
        <i class="fa fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=Analysis%20of%20Beer%20Reviews&amp;body=%2fr%2fbeer-reviews-analysis%2f">
        <i class="fa fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>


    <div class="article-style" itemprop="articleBody">
      <div id="TOC">
<ul>
<li><a href="#data-download">Data Download</a></li>
<li><a href="#the-variables">The Variables</a></li>
<li><a href="#data-cleaning">Data Cleaning</a></li>
<li><a href="#exploratory">Exploratory</a></li>
<li><a href="#r-session-info">R Session Info</a></li>
</ul>
</div>

<pre class="r"><code>library(corrplot)
library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(ggplot2)
library(Hmisc)</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## Loading required package: survival</code></pre>
<pre><code>## Loading required package: Formula</code></pre>
<pre><code>## 
## Attaching package: &#39;Hmisc&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     combine, src, summarize</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     format.pval, round.POSIXt, trunc.POSIXt, units</code></pre>
<pre class="r"><code>library(purrr)
library(rvest)</code></pre>
<pre><code>## Loading required package: xml2</code></pre>
<pre><code>## 
## Attaching package: &#39;rvest&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     pluck</code></pre>
<pre><code>## The following object is masked from &#39;package:Hmisc&#39;:
## 
##     html</code></pre>
<pre class="r"><code>library(stringr)
library(xml2)</code></pre>
<p><a href="https://www.linkedin.com/pulse/how-hire-test-data-skills-one-size-fits-all-interview-tanya-cashorali/">One-Size-Fits-All Interview Kit</a></p>
<div id="data-download" class="section level3">
<h3>Data Download</h3>
<p>Data courtesy of <a href="http://www.beeradvocate.com/">Beer Advocate</a>.</p>
<pre class="r"><code>#&#39; Path to download csv
data_dir &lt;- &quot;~/Downloads&quot;

local_file &lt;- sprintf(&quot;%s/beer_reviews.csv&quot;, data_dir)

if (file.exists(local_file)) {
  df &lt;- readr::read_csv(local_file)
  
} else {

  url &lt;- &quot;https://github.com/timtrice/datasets/blob/master/beer_reviews/beer_reviews.tar.gz?raw=true&quot;
  destdir &lt;- tempdir()
  utils::download.file(file.path(url), zip_file &lt;- tempfile())
  utils::untar(zip_file, exdir = destdir)
  df &lt;- readr::read_csv(sprintf(&quot;%s/beer_reviews/beer_reviews.csv&quot;, destdir))
  
  if (!dir.exists(data_dir)) 
    dir.create(data_dir)
  
  readr::write_csv(df, file.path(local_file))

}</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   brewery_id = col_integer(),
##   brewery_name = col_character(),
##   review_time = col_integer(),
##   review_overall = col_double(),
##   review_aroma = col_double(),
##   review_appearance = col_double(),
##   review_profilename = col_character(),
##   beer_style = col_character(),
##   review_palate = col_double(),
##   review_taste = col_double(),
##   beer_name = col_character(),
##   beer_abv = col_double(),
##   beer_beerid = col_integer()
## )</code></pre>
</div>
<div id="the-variables" class="section level3">
<h3>The Variables</h3>
<pre class="r"><code>str(df)</code></pre>
<pre><code>## Classes &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;:    1586614 obs. of  13 variables:
##  $ brewery_id        : int  10325 10325 10325 10325 1075 1075 1075 1075 1075 1075 ...
##  $ brewery_name      : chr  &quot;Vecchio Birraio&quot; &quot;Vecchio Birraio&quot; &quot;Vecchio Birraio&quot; &quot;Vecchio Birraio&quot; ...
##  $ review_time       : int  1234817823 1235915097 1235916604 1234725145 1293735206 1325524659 1318991115 1306276018 1290454503 1285632924 ...
##  $ review_overall    : num  1.5 3 3 3 4 3 3.5 3 4 4.5 ...
##  $ review_aroma      : num  2 2.5 2.5 3 4.5 3.5 3.5 2.5 3 3.5 ...
##  $ review_appearance : num  2.5 3 3 3.5 4 3.5 3.5 3.5 3.5 5 ...
##  $ review_profilename: chr  &quot;stcules&quot; &quot;stcules&quot; &quot;stcules&quot; &quot;stcules&quot; ...
##  $ beer_style        : chr  &quot;Hefeweizen&quot; &quot;English Strong Ale&quot; &quot;Foreign / Export Stout&quot; &quot;German Pilsener&quot; ...
##  $ review_palate     : num  1.5 3 3 2.5 4 3 4 2 3.5 4 ...
##  $ review_taste      : num  1.5 3 3 3 4.5 3.5 4 3.5 4 4 ...
##  $ beer_name         : chr  &quot;Sausa Weizen&quot; &quot;Red Moon&quot; &quot;Black Horse Black Beer&quot; &quot;Sausa Pils&quot; ...
##  $ beer_abv          : num  5 6.2 6.5 5 7.7 4.7 4.7 4.7 4.7 4.7 ...
##  $ beer_beerid       : int  47986 48213 48215 47969 64883 52159 52159 52159 52159 52159 ...
##  - attr(*, &quot;spec&quot;)=List of 2
##   ..$ cols   :List of 13
##   .. ..$ brewery_id        : list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_integer&quot; &quot;collector&quot;
##   .. ..$ brewery_name      : list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_character&quot; &quot;collector&quot;
##   .. ..$ review_time       : list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_integer&quot; &quot;collector&quot;
##   .. ..$ review_overall    : list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_double&quot; &quot;collector&quot;
##   .. ..$ review_aroma      : list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_double&quot; &quot;collector&quot;
##   .. ..$ review_appearance : list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_double&quot; &quot;collector&quot;
##   .. ..$ review_profilename: list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_character&quot; &quot;collector&quot;
##   .. ..$ beer_style        : list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_character&quot; &quot;collector&quot;
##   .. ..$ review_palate     : list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_double&quot; &quot;collector&quot;
##   .. ..$ review_taste      : list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_double&quot; &quot;collector&quot;
##   .. ..$ beer_name         : list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_character&quot; &quot;collector&quot;
##   .. ..$ beer_abv          : list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_double&quot; &quot;collector&quot;
##   .. ..$ beer_beerid       : list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_integer&quot; &quot;collector&quot;
##   ..$ default: list()
##   .. ..- attr(*, &quot;class&quot;)= chr  &quot;collector_guess&quot; &quot;collector&quot;
##   ..- attr(*, &quot;class&quot;)= chr &quot;col_spec&quot;</code></pre>
<div id="brewery_id" class="section level4">
<h4>brewery_id</h4>
<pre class="r"><code>describe(df$brewery_id)</code></pre>
<pre><code>## df$brewery_id 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##  1586614        0     5840        1     3130     4731       30       45 
##      .25      .50      .75      .90      .95 
##      143      429     2372    12516    16866 
## 
## lowest :     1     2     3     4     5, highest: 27945 27980 27984 28000 28003</code></pre>
<ul>
<li><p>continuous variable</p></li>
<li><p>There are no missing <code>brewer_id</code> values.</p></li>
<li><p>The mean is higher than 75% of the values so there is a heavy skew along the lower values for some reason. Question: <em>Why is this? Is this relevant?</em></p></li>
</ul>
<pre class="r"><code>ggplot(df, aes(x = brewery_id)) + geom_histogram(bins = 50)</code></pre>
<p><img src="../../R/beer-reviews-analysis_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="brewery_name" class="section level4">
<h4>brewery_name</h4>
<pre class="r"><code>describe(df$brewery_name)</code></pre>
<pre><code>## df$brewery_name 
##        n  missing distinct 
##  1586599       15     5742 
## 
## lowest : &#39;t Hofbrouwerijke                 (512) Brewing Company             10 Barrel Brewing Co.             1516 Brewing Company              16 Mile Brewing Company          
## highest: Zum Löwenbräu                     Zum Stiefel                       Zuma Brewing Company              Zweite Schweriner Schlossbrauerei Zywiec Breweries PLC (Heineken)</code></pre>
<ul>
<li>Categorical variables</li>
</ul>
<p>My expectation was for the numbers <code>n</code>, <code>missing</code> and <code>distinct</code> to match up with <code>brewery_id</code>, but they don’t. While the <code>missing</code> count is only slightly off (-15), the <code>distinct</code> count is way off (-98).</p>
<pre class="r"><code>unique(df$brewery_id[is.na(df$brewery_name)])</code></pre>
<pre><code>## [1] 1193   27</code></pre>
<p>There are only 2 missing unique <code>brewer_id</code>.</p>
<p>The discrepancy suggests some brewery’s may have multiple names for the same id.</p>
<pre class="r"><code>df %&gt;% 
  group_by(brewery_id) %&gt;% 
  summarise(n = length(unique(brewery_name))) %&gt;% 
  filter(n &gt; 1)</code></pre>
<pre><code>## # A tibble: 0 x 2
## # ... with 2 variables: brewery_id &lt;int&gt;, n &lt;int&gt;</code></pre>
<p>My instinct is wrong. I’ll flip it.</p>
<pre class="r"><code>df %&gt;% 
  group_by(brewery_name) %&gt;% 
  summarise(n = length(unique(brewery_id))) %&gt;% 
  filter(n &gt; 1) %&gt;% 
  arrange(brewery_name)</code></pre>
<pre><code>## # A tibble: 60 x 2
##                           brewery_name     n
##                                  &lt;chr&gt; &lt;int&gt;
##  1                 Back Street Brewery     4
##  2                Baja Brewing Company     2
##  3          Bare Bones Grill &amp; Brewery     2
##  4    Big River Grille &amp; Brewing Works     3
##  5           BJ&#39;s Restaurant &amp; Brewery     4
##  6         BJ&#39;s Restaurant &amp; Brewhouse     3
##  7       BJ&#39;s Restaurant And Brewhouse     2
##  8 Brew Moon Restaurant &amp; Microbrewery     2
##  9                        C.B. &amp; Potts     3
## 10                Capitol City Brewing     3
## # ... with 50 more rows</code></pre>
<p>Ok, so 60 <code>brewery_name</code> have multiple <code>brewery_id</code>. There are also spelling discrepancies, e.g., BJ’s Restaurant &amp; Brewery, BJ’s Restaurant &amp; Brewhouse, BJ’s Restaurant And Brewhouse. These discrepancies will need to be cleaned.</p>
</div>
<div id="review_time" class="section level4">
<h4>review_time</h4>
<pre class="r"><code>describe(df$review_time)</code></pre>
<pre><code>## df$review_time 
##         n   missing  distinct      Info      Mean       Gmd       .05 
##   1586614         0   1577960         1 1.224e+09  85515630 1.071e+09 
##       .10       .25       .50       .75       .90       .95 
## 1.107e+09 1.173e+09 1.239e+09 1.289e+09 1.311e+09 1.318e+09 
## 
## lowest :  840672001  884390401  884649601  885340801  885427201
## highest: 1326274454 1326275049 1326276656 1326284970 1326285348</code></pre>
<pre class="r"><code>ggplot(df, aes(x = review_time)) + geom_histogram(bins = 10000)</code></pre>
<p><img src="../../R/beer-reviews-analysis_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="review_overall" class="section level4">
<h4>review_overall</h4>
<pre class="r"><code>describe(df$review_overall)</code></pre>
<pre><code>## df$review_overall 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##  1586614        0       10    0.934    3.816   0.7584      2.5      3.0 
##      .25      .50      .75      .90      .95 
##      3.5      4.0      4.5      4.5      5.0 
##                                                                          
## Value         0.0    1.0    1.5    2.0    2.5    3.0    3.5    4.0    4.5
## Frequency       7  10954  12975  38225  58523 165644 301817 582764 324385
## Proportion  0.000  0.007  0.008  0.024  0.037  0.104  0.190  0.367  0.204
##                  
## Value         5.0
## Frequency   91320
## Proportion  0.058</code></pre>
<pre class="r"><code>ggplot(df, aes(x = review_overall)) + geom_bar()</code></pre>
<p><img src="../../R/beer-reviews-analysis_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<ul>
<li>Categorical</li>
</ul>
</div>
<div id="review_aroma" class="section level4">
<h4>review_aroma</h4>
<pre class="r"><code>describe(df$review_aroma)</code></pre>
<pre><code>## df$review_aroma 
##        n  missing distinct     Info     Mean      Gmd 
##  1586614        0        9    0.937    3.736    0.744 
##                                                                          
## Value         1.0    1.5    2.0    2.5    3.0    3.5    4.0    4.5    5.0
## Frequency    6873  12524  42566  66359 200030 365312 557383 271450  64117
## Proportion  0.004  0.008  0.027  0.042  0.126  0.230  0.351  0.171  0.040</code></pre>
<pre class="r"><code>ggplot(df, aes(x = review_aroma)) + geom_bar()</code></pre>
<p><img src="../../R/beer-reviews-analysis_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<ul>
<li>Categorical</li>
</ul>
</div>
<div id="review_appearance" class="section level4">
<h4>review_appearance</h4>
<pre class="r"><code>describe(df$review_appearance)</code></pre>
<pre><code>## df$review_appearance 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##  1586614        0       10    0.908    3.842   0.6436      3.0      3.0 
##      .25      .50      .75      .90      .95 
##      3.5      4.0      4.0      4.5      4.5 
##                                                                          
## Value         0.0    1.0    1.5    2.0    2.5    3.0    3.5    4.0    4.5
## Frequency       7   3323   6147  25414  39493 166009 318529 674186 288108
## Proportion  0.000  0.002  0.004  0.016  0.025  0.105  0.201  0.425  0.182
##                  
## Value         5.0
## Frequency   65398
## Proportion  0.041</code></pre>
<pre class="r"><code>ggplot(df, aes(x = review_appearance)) + geom_bar()</code></pre>
<p><img src="../../R/beer-reviews-analysis_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<ul>
<li>Categorical</li>
</ul>
</div>
<div id="review_profilename" class="section level4">
<h4>review_profilename</h4>
<pre class="r"><code>describe(df$review_profilename)</code></pre>
<pre><code>## df$review_profilename 
##        n  missing distinct 
##  1586266      348    33387 
## 
## lowest : 0110x011    01Ryan10    02maxima    03SVTCobra  04101Brewer
## highest: zythus      Zywiec06    zyzygy      zzajjber    Zzyzx</code></pre>
<ul>
<li>Categorical</li>
</ul>
</div>
<div id="beer_style" class="section level4">
<h4>beer_style</h4>
<pre class="r"><code>describe(df$beer_style)</code></pre>
<pre><code>## df$beer_style 
##        n  missing distinct 
##  1586614        0      104 
## 
## lowest : Altbier                    American Adjunct Lager     American Amber / Red Ale   American Amber / Red Lager American Barleywine       
## highest: Vienna Lager               Weizenbock                 Wheatwine                  Winter Warmer              Witbier</code></pre>
<ul>
<li>Categorical</li>
</ul>
</div>
<div id="review_palate" class="section level4">
<h4>review_palate</h4>
<pre class="r"><code>describe(df$review_palate)</code></pre>
<pre><code>## df$review_palate 
##        n  missing distinct     Info     Mean      Gmd 
##  1586614        0        9    0.928    3.744   0.7227 
##                                                                          
## Value         1.0    1.5    2.0    2.5    3.0    3.5    4.0    4.5    5.0
## Frequency    6874  11045  38333  62842 206932 338585 606711 253102  62190
## Proportion  0.004  0.007  0.024  0.040  0.130  0.213  0.382  0.160  0.039</code></pre>
<pre class="r"><code>ggplot(df, aes(x = review_palate)) + geom_bar()</code></pre>
<p><img src="../../R/beer-reviews-analysis_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<ul>
<li>Categorical</li>
</ul>
</div>
<div id="review_taste" class="section level4">
<h4>review_taste</h4>
<pre class="r"><code>describe(df$review_taste)</code></pre>
<pre><code>## df$review_taste 
##        n  missing distinct     Info     Mean      Gmd 
##  1586614        0        9    0.941    3.793   0.7766 
##                                                                          
## Value         1.0    1.5    2.0    2.5    3.0    3.5    4.0    4.5    5.0
## Frequency    9991  15128  41992  66534 166860 324541 541429 336162  83977
## Proportion  0.006  0.010  0.026  0.042  0.105  0.205  0.341  0.212  0.053</code></pre>
<pre class="r"><code>ggplot(df, aes(x = review_taste)) + geom_bar()</code></pre>
<p><img src="../../R/beer-reviews-analysis_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<ul>
<li>Categorical</li>
</ul>
</div>
<div id="beer_abv" class="section level4">
<h4>beer_abv</h4>
<pre class="r"><code>describe(df$beer_abv)</code></pre>
<pre><code>## df$beer_abv 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##  1518829    67785      530    0.999    7.042     2.47      4.5      4.8 
##      .25      .50      .75      .90      .95 
##      5.2      6.5      8.5     10.0     11.0 
## 
## lowest :  0.01  0.05  0.08  0.10  0.25, highest: 39.00 39.44 41.00 43.00 57.70</code></pre>
<pre class="r"><code>df %&gt;% 
  filter(!is.na(beer_abv)) %&gt;% 
  ggplot(aes(x = beer_abv)) + 
  geom_freqpoly(bins = 10)</code></pre>
<p><img src="../../R/beer-reviews-analysis_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<ul>
<li>Continuous</li>
</ul>
</div>
<div id="beer_name" class="section level4">
<h4>beer_name</h4>
<pre class="r"><code>describe(df$beer_name)</code></pre>
<pre><code>## df$beer_name 
##        n  missing distinct 
##  1586614        0    56857 
## 
## lowest : ! (Old Ale)                       ? (Imperial Bitter)               ? The Riddler ?                   ¿Por Que No?                      .357 Imperial Pilsner            
## highest: ZZ Lager                          Þorrabjór                         Ω-naught (Omeganaught)            横須賀ビアサケ (Yokosuka Biasake) 葉山ビール (Hayama Beer)</code></pre>
</div>
<div id="beer_beerid" class="section level4">
<h4>beer_beerid</h4>
<pre class="r"><code>describe(df$beer_beerid)</code></pre>
<pre><code>## df$beer_beerid 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##  1586614        0    66055        1    21713    23983      213      577 
##      .25      .50      .75      .90      .95 
##     1717    13906    39441    55183    62653 
## 
## lowest :     3     4     5     6     7, highest: 77313 77314 77315 77316 77317</code></pre>
<pre class="r"><code>ggplot(df, aes(x = beer_beerid)) + geom_histogram(bins = 50)</code></pre>
<p><img src="../../R/beer-reviews-analysis_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
</div>
</div>
<div id="data-cleaning" class="section level3">
<h3>Data Cleaning</h3>
<p>There are four variables I’m most concerned about that will need to be cleaned: <code>brewery_id</code>, <code>brewery_name</code>, <code>beer_name</code> and <code>beer_beerid</code>.</p>
<p>Recall again the list of brewery names that had more than one brewery id:</p>
<pre class="r"><code>df %&gt;% 
  group_by(brewery_name) %&gt;% 
  summarise(n = length(unique(brewery_id))) %&gt;% 
  filter(n &gt; 1) %&gt;% 
  arrange(brewery_name)</code></pre>
<pre><code>## # A tibble: 60 x 2
##                           brewery_name     n
##                                  &lt;chr&gt; &lt;int&gt;
##  1                 Back Street Brewery     4
##  2                Baja Brewing Company     2
##  3          Bare Bones Grill &amp; Brewery     2
##  4    Big River Grille &amp; Brewing Works     3
##  5           BJ&#39;s Restaurant &amp; Brewery     4
##  6         BJ&#39;s Restaurant &amp; Brewhouse     3
##  7       BJ&#39;s Restaurant And Brewhouse     2
##  8 Brew Moon Restaurant &amp; Microbrewery     2
##  9                        C.B. &amp; Potts     3
## 10                Capitol City Brewing     3
## # ... with 50 more rows</code></pre>
<p>I established earlier that brewery id’s only have one unique brewery name. I’ll go through each name on this list and try to iron out the discrepancies.</p>
<div id="brewery-name-data-validation" class="section level4">
<h4>Brewery Name Data Validation</h4>
<p>I’ll start first with “Back Street Brewery”. I want to list all distinct <code>brewery_name</code> values that begin with “Back St” (use the common St abbreviation to capture both St and Street).</p>
<pre class="r"><code>df %&gt;% 
  filter(grepl(&quot;^Back St&quot;, brewery_name)) %&gt;% 
  select(starts_with(&quot;b&quot;)) %&gt;% 
  distinct(brewery_name, .keep_all = TRUE)</code></pre>
<pre><code>## # A tibble: 1 x 6
##   brewery_id        brewery_name beer_style beer_name beer_abv beer_beerid
##        &lt;int&gt;               &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;       &lt;int&gt;
## 1       4410 Back Street Brewery    Altbier       Alt       NA       58971</code></pre>
<p>There is only one Back St. What about distinct <code>brewery_id</code> values?</p>
<pre class="r"><code>df %&gt;% 
  filter(grepl(&quot;^Back St&quot;, brewery_name)) %&gt;% 
  select(starts_with(&quot;b&quot;)) %&gt;% 
  distinct(brewery_id, .keep_all = TRUE)</code></pre>
<pre><code>## # A tibble: 4 x 6
##   brewery_id        brewery_name               beer_style
##        &lt;int&gt;               &lt;chr&gt;                    &lt;chr&gt;
## 1       4410 Back Street Brewery                  Altbier
## 2      15327 Back Street Brewery               Hefeweizen
## 3      12164 Back Street Brewery American Amber / Red Ale
## 4      10012 Back Street Brewery  Belgian Strong Dark Ale
## # ... with 3 more variables: beer_name &lt;chr&gt;, beer_abv &lt;dbl&gt;,
## #   beer_beerid &lt;int&gt;</code></pre>
<p>Ok, there are a few different <code>brewery_id</code> values for this brewery. I’m a bit stuck on how I can validate the legitimacy (or lack thereof) on these values.</p>
<p>Are there multiple “Back Street Brewery”? Or, is this a crowd-sourcing error (Yelp is bad with this, too).</p>
<p>Thankfully, the Beer Advocate website happens to have addresses. We can plug <code>brewery_id</code> into a URL and scrape the address info.</p>
<p>Let me go grab the brewery ids.</p>
<pre class="r"><code>brewery_ids &lt;- df %&gt;% 
  filter(grepl(&quot;^Back St&quot;, brewery_name)) %&gt;% 
  select(starts_with(&quot;brew&quot;)) %&gt;% 
  distinct() %&gt;% 
  pull(brewery_id)

brewery_ids</code></pre>
<pre><code>## [1]  4410 15327 12164 10012</code></pre>
<p>Now I’ll write a little scraping function that will return the addresses for each of the breweries.</p>
<pre class="r"><code>get_addresses &lt;- function(brewery_id) {

  url &lt;- glue::glue(&quot;https://www.beeradvocate.com/beer/profile/{brewery_id}/&quot;)
  
  xml2::read_html(url) %&gt;% 
    rvest::html_nodes(xpath = &quot;//*[(@id = &#39;info_box&#39;)]&quot;) %&gt;% 
    rvest::html_text()
}</code></pre>
<p>Get the addresses.</p>
<pre class="r"><code>addresses &lt;- map(brewery_ids, get_addresses) %&gt;% 
  trimws() %&gt;% 
  str_split(pattern = &quot;[:cntrl:]+&quot;) %&gt;% 
  # All address info seems to be in the 3rd element so just grab those.
  map(`[`, 3)

addresses</code></pre>
<pre><code>## [[1]]
## [1] &quot;14450 Culver DriveIrvine, California, 92604United States(949) 857-0160 | maplamppostpizza.com&quot;
## 
## [[2]]
## [1] &quot;78-772 Highway 111La Quinta, California, 92253United States(760) 564-4568 | maplamppostpizza.com&quot;
## 
## [[3]]
## [1] &quot;15 Main Street, Suite #100Vista, California, 92084United States(760) 407-7600 | maplamppostpizza.com&quot;
## 
## [[4]]
## [1] &quot;27702 Crown Valley ParkwayLadera Ranch, California, 92691United States(949) 388-7260 // CLOSED //&quot;</code></pre>
<p>I can do a visual analysis and see none of these are a match. In other words, it looks like we’re dealing with a franchise. With that said, “Back Street Brewery” should not be corrected.</p>
<p>I’m going to modify <code>get_addresses()</code> to take the pattern I’m searching (in the example above, “^Back St”) and just return the results. I don’t want to keep typing all of that code.</p>
<pre class="r"><code>#&#39; @title get_addresses
#&#39; @description Given a dataframe (x) and a pattern for brewery_name, will 
#&#39;    return all addresses for breweries that match that pattern.
#&#39; @param x Dataframe object
#&#39; @pattern regex pattern for brewery names to find
get_addresses &lt;- function(x, pattern) {
  x %&gt;% 
  filter(grepl(pattern, brewery_name)) %&gt;% 
  select(starts_with(&quot;brew&quot;)) %&gt;% 
  distinct() %&gt;% 
  pull(brewery_id) %&gt;% 
  sprintf(&quot;https://www.beeradvocate.com/beer/profile/%s/&quot;, .) %&gt;% 
  map(read_html) %&gt;% 
  map(html_nodes, xpath = &quot;//*[(@id = &#39;info_box&#39;)]&quot;) %&gt;% 
  map(html_text) %&gt;% 
  str_split(pattern = &quot;[:cntrl:]+&quot;) %&gt;% 
  map(`[`, 4)
}</code></pre>
<p>I’ll test it.</p>
<pre class="r"><code>get_addresses(df, &quot;^Back St&quot;)</code></pre>
<pre><code>## [[1]]
## [1] &quot;14450 Culver DriveIrvine, California, 92604United States(949) 857-0160 | maplamppostpizza.com&quot;
## 
## [[2]]
## [1] &quot;78-772 Highway 111La Quinta, California, 92253United States(760) 564-4568 | maplamppostpizza.com&quot;
## 
## [[3]]
## [1] &quot;15 Main Street, Suite #100Vista, California, 92084United States(760) 407-7600 | maplamppostpizza.com&quot;
## 
## [[4]]
## [1] &quot;27702 Crown Valley ParkwayLadera Ranch, California, 92691United States(949) 388-7260 // CLOSED //&quot;</code></pre>
<p>[[satisfied face meme]]</p>
<p>Ok, now I just need to go through our discrepancies. It would be nice to write a function to do this as well. But the pattern requires human involvement; oh, well.</p>
<p>Of the known items with possible issues, only those that immediately follow had true issues.</p>
<div id="bare-bones-grill-brewery" class="section level5">
<h5>Bare Bones Grill &amp; Brewery</h5>
<pre class="r"><code>ptn &lt;- &quot;^Bare\\s&quot;</code></pre>
<pre class="r"><code>#&#39; Find all possible matches
df %&gt;% filter(grepl(ptn, brewery_name)) %&gt;% 
  select(starts_with(&quot;brew&quot;)) %&gt;% 
  distinct(brewery_id, .keep_all = TRUE)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   brewery_id               brewery_name
##        &lt;int&gt;                      &lt;chr&gt;
## 1       1953 Bare Bones Grill &amp; Brewery
## 2       1954 Bare Bones Grill &amp; Brewery</code></pre>
<pre class="r"><code>#&#39; List addresses
get_addresses(df, ptn)</code></pre>
<pre><code>## Error in open.connection(x, &quot;rb&quot;): HTTP error 404.</code></pre>
<p>In this case, the page for id 1953 no longer exists. So, there is no way to validate the discrepancy. In this case I will update all 1953 <code>brewery_id</code> values to 1954.</p>
<pre class="r"><code>df$brewery_id[df$brewery_id == 1953] &lt;- 1954</code></pre>
<pre><code>## Warning: closing unused connection 5 (https://www.beeradvocate.com/beer/
## profile/1953/)</code></pre>
</div>
</div>
<div id="rocky-coulee-brewing-co." class="section level4">
<h4>Rocky Coulee Brewing Co.</h4>
<pre class="r"><code>ptn &lt;- &quot;^Rocky\\sC&quot;</code></pre>
<pre class="r"><code>#&#39; Find all possible matches
df %&gt;% filter(grepl(ptn, brewery_name)) %&gt;% 
  select(starts_with(&quot;brew&quot;)) %&gt;% 
  distinct(brewery_id, .keep_all = TRUE)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   brewery_id             brewery_name
##        &lt;dbl&gt;                    &lt;chr&gt;
## 1      13094 Rocky Coulee Brewing Co.
## 2      12984 Rocky Coulee Brewing Co.</code></pre>
<pre class="r"><code>#&#39; List addresses
get_addresses(df, ptn)</code></pre>
<pre><code>## [[1]]
## [1] &quot;205 N. First StreetOdessa, Washington, 99159United States(509) 345-2216 | maprockycouleebrewingco.com&quot;
## 
## [[2]]
## [1] &quot;205 N. First StreetOdessa, Washington, 99159United States(509) 346-2216 // CLOSED //&quot;</code></pre>
<p>“Rocky Coulee Brewing Co.” has two identical entries in the database. The only difference in the address listings is one digit in the phone number.</p>
<p>I’ll update those with <code>brewery_id</code> 13094 to 12984.</p>
<pre class="r"><code>df$brewery_id[df$brewery_id == 13094] &lt;- 12984</code></pre>
</div>
</div>
<div id="exploratory" class="section level3">
<h3>Exploratory</h3>
<pre class="r"><code>cc &lt;- df[complete.cases(df),] %&gt;% 
  select(starts_with(&quot;review&quot;), -review_time, -review_profilename, beer_abv)</code></pre>
<pre class="r"><code>cor(cc)</code></pre>
<pre><code>##                   review_overall review_aroma review_appearance
## review_overall         1.0000000    0.6127926         0.4985565
## review_aroma           0.6127926    1.0000000         0.5590771
## review_appearance      0.4985565    0.5590771         1.0000000
## review_palate          0.6990197    0.6149238         0.5645551
## review_taste           0.7871712    0.7147773         0.5445794
## beer_abv               0.1384574    0.3325362         0.2638906
##                   review_palate review_taste  beer_abv
## review_overall        0.6990197    0.7871712 0.1384574
## review_aroma          0.6149238    0.7147773 0.3325362
## review_appearance     0.5645551    0.5445794 0.2638906
## review_palate         1.0000000    0.7322005 0.2866673
## review_taste          0.7322005    1.0000000 0.2907817
## beer_abv              0.2866673    0.2907817 1.0000000</code></pre>
<p>Most positive relationship seems to be between <code>review_overall</code> and <code>review_taste</code>. I want to take the mean <code>review_overall</code> and <code>review_taste</code> per <code>beer_beerid</code> and draw a scatterplot.</p>
<pre class="r"><code>df %&gt;% 
  group_by(beer_beerid) %&gt;% 
  summarise(mean_review_overall = mean(review_overall, na.rm = TRUE), 
            mean_review_taste = mean(review_taste, na.rm = TRUE)) %&gt;% 
  ggplot(aes(x = mean_review_overall, y = mean_review_taste)) + 
  geom_point() + 
  geom_smooth()</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39;</code></pre>
<p><img src="../../R/beer-reviews-analysis_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p>Is this really surprising?</p>
<p>Next to taste is <code>review_palate</code>; let’s check that out.</p>
<pre class="r"><code>df %&gt;% 
  group_by(beer_beerid) %&gt;% 
  summarise(mean_review_overall = mean(review_overall, na.rm = TRUE), 
            mean_review_aroma = mean(review_aroma, na.rm = TRUE)) %&gt;% 
  ggplot(aes(x = mean_review_overall, y = mean_review_aroma)) + 
  geom_point() + 
  geom_smooth()</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39;</code></pre>
<p><img src="../../R/beer-reviews-analysis_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>I’m curious what type of</p>
<pre class="r"><code>df %&gt;% 
  select(beer_beerid, review_overall, review_aroma, review_taste) %&gt;% 
  mutate(
    review_class = case_when(
      review_overall &lt; 1 ~ &quot;A&quot;, 
      review_overall &lt; 2 ~ &quot;B&quot;, 
      review_overall &lt; 3 ~ &quot;C&quot;, 
      review_overall &lt; 4 ~ &quot;D&quot;, 
      TRUE ~ &quot;E&quot;)) %&gt;% 
  group_by(beer_beerid) %&gt;% 
  summarise(mean_review_aroma = mean(review_aroma, na.rm = TRUE)) %&gt;% 
  ggplot(aes(x = review_class, y = mean_review_aroma)) %&gt;% 
  geom_boxplot()</code></pre>
<pre><code>## Error: Mapping must be created by `aes()` or `aes_()`</code></pre>
</div>
<div id="r-session-info" class="section level2">
<h2>R Session Info</h2>
<pre class="r"><code>pander::pander(sessionInfo())</code></pre>
<p><strong>R version 3.4.1 (2017-06-30)</strong></p>
<p>**<a href="Platform:**" class="uri">Platform:**</a> x86_64-pc-linux-gnu (64-bit)</p>
<p><strong>locale:</strong> <em>LC_CTYPE=en_US.UTF-8</em>, <em>LC_NUMERIC=C</em>, <em>LC_TIME=en_US.UTF-8</em>, <em>LC_COLLATE=en_US.UTF-8</em>, <em>LC_MONETARY=en_US.UTF-8</em>, <em>LC_MESSAGES=C</em>, <em>LC_PAPER=en_US.UTF-8</em>, <em>LC_NAME=C</em>, <em>LC_ADDRESS=C</em>, <em>LC_TELEPHONE=C</em>, <em>LC_MEASUREMENT=en_US.UTF-8</em> and <em>LC_IDENTIFICATION=C</em></p>
<p><strong>attached base packages:</strong> <em>methods</em>, <em>stats</em>, <em>graphics</em>, <em>grDevices</em>, <em>utils</em>, <em>datasets</em> and <em>base</em></p>
<p><strong>other attached packages:</strong> <em>bindrcpp(v.0.2)</em>, <em>stringr(v.1.2.0)</em>, <em>rvest(v.0.3.2)</em>, <em>xml2(v.1.1.1)</em>, <em>purrr(v.0.2.3)</em>, <em>Hmisc(v.4.0-3)</em>, <em>Formula(v.1.2-2)</em>, <em>survival(v.2.41-3)</em>, <em>lattice(v.0.20-35)</em>, <em>ggplot2(v.2.2.1)</em>, <em>dplyr(v.0.7.4)</em> and <em>corrplot(v.0.77)</em></p>
<p><strong>loaded via a namespace (and not attached):</strong> <em>pander(v.0.6.1)</em>, <em>splines(v.3.4.1)</em>, <em>colorspace(v.1.3-2)</em>, <em>htmltools(v.0.3.6)</em>, <em>mgcv(v.1.8-22)</em>, <em>yaml(v.2.1.14)</em>, <em>base64enc(v.0.1-3)</em>, <em>rlang(v.0.1.2)</em>, <em>foreign(v.0.8-69)</em>, <em>glue(v.1.1.1)</em>, <em>RColorBrewer(v.1.1-2)</em>, <em>bindr(v.0.1)</em>, <em>plyr(v.1.8.4)</em>, <em>munsell(v.0.4.3)</em>, <em>blogdown(v.0.1)</em>, <em>gtable(v.0.2.0)</em>, <em>htmlwidgets(v.0.9)</em>, <em>evaluate(v.0.10.1)</em>, <em>labeling(v.0.3)</em>, <em>latticeExtra(v.0.6-28)</em>, <em>knitr(v.1.17)</em>, <em>curl(v.2.8.1)</em>, <em>htmlTable(v.1.9)</em>, <em>Rcpp(v.0.12.13)</em>, <em>acepack(v.1.4.1)</em>, <em>readr(v.1.1.1)</em>, <em>scales(v.0.5.0)</em>, <em>backports(v.1.1.1)</em>, <em>checkmate(v.1.8.4)</em>, <em>gridExtra(v.2.3)</em>, <em>hms(v.0.3)</em>, <em>digest(v.0.6.12)</em>, <em>stringi(v.1.1.5)</em>, <em>bookdown(v.0.5)</em>, <em>grid(v.3.4.1)</em>, <em>rprojroot(v.1.2)</em>, <em>tools(v.3.4.1)</em>, <em>magrittr(v.1.5)</em>, <em>lazyeval(v.0.2.0)</em>, <em>tibble(v.1.3.4)</em>, <em>cluster(v.2.0.6)</em>, <em>pkgconfig(v.2.0.1)</em>, <em>Matrix(v.1.2-11)</em>, <em>data.table(v.1.10.4)</em>, <em>assertthat(v.0.2.0)</em>, <em>rmarkdown(v.1.6)</em>, <em>httr(v.1.3.1)</em>, <em>R6(v.2.2.2)</em>, <em>rpart(v.4.1-11)</em>, <em>nlme(v.3.1-131)</em>, <em>nnet(v.7.3-12)</em> and <em>compiler(v.3.4.1)</em></p>
</div>

    </div>

    


    
    

    
    <div class="article-widget">
      <div class="post-nav">
  
  
</div>

    </div>
    

    
<section id="comments">
  <div id="disqus_thread"></div>
<script>
    var disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "timtrice" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</section>



  </div>
</article>

<footer class="site-footer">
  <div class="container">
    <p class="powered-by">

      &copy; 2018 &middot; 

      Powered by the
      <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
      <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

      <span class="pull-right" aria-hidden="true">
        <a href="#" id="back_to_top">
          <span class="button_icon">
            <i class="fa fa-chevron-up fa-2x"></i>
          </span>
        </a>
      </span>

    </p>
  </div>
</footer>


<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close btn-large" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Cite</h4>
      </div>
      <div>
        <pre><code class="modal-body tex"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary btn-outline js-copy-cite" href="#" target="_blank">
          <i class="fa fa-copy"></i> Copy
        </a>
        <a class="btn btn-primary btn-outline js-download-cite" href="#" target="_blank">
          <i class="fa fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

    

    
    
    <script id="dsq-count-scr" src="//timtrice.disqus.com/count.js" async></script>
    

    

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha512-3P8rXCuGJdNZOnUx/03c1jOTnMn3rP63nBip5gOP2qmUh5YAdVAvFZ1E+QLZZbC1rtMrQb+mah3AfYW11RUrWA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.3/imagesloaded.pkgd.min.js" integrity="sha512-umsR78NN0D23AzgoZ11K7raBD+R6hqKojyBZs1w8WvYlsI+QuKRGBx3LFCwhatzBunCjDuJpDHwxD13sLMbpRA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha512-iztkobsvnjKfAtTNdHkGVjAYTrrtlC7mGp/54c40wowO7LhURYl3gVzzcEqGl/qKXQltJ2HwMrdLcNUdo+N/RQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.4/isotope.pkgd.min.js" integrity="sha512-VDBOIlDbuC4VWxGJNmuFRQ0Li0SKkDpmGyuhAG5LTDLd/dJ/S0WMVxriR2Y+CyPL5gzjpN4f/6iqWVBJlht0tQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>
    
    
    <script src="../../js/hugo-academic.js"></script>
    

    
    
      
      
      <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>
      

      

      

      <script>hljs.initHighlightingOnLoad();</script>
    

    
    

  </body>
</html>

