
```{r db_libraries, include = FALSE}
library(DBI)
library(RMySQL)
```

```{r mysql-con_params, include = FALSE}
mysql.host <- Sys.getenv("mysql.host")
mysql.user <- Sys.getenv("mysql.user")
mysql.password <- Sys.getenv("mysql.password")
```

```{r mysql-con, include = FALSE}
mysql_con <- dbConnect(RMySQL::MySQL(), 
                 host = mysql.host,
                 user = mysql.user, 
                 password = mysql.password)
```

```{sql setup-instruments-statement, echo = FALSE, eval = FALSE}
-- Disabled
-- See https://dev.mysql.com/doc/refman/5.6/en/performance-schema-query-profiling.html
UPDATE `performance_schema`.`setup_instruments`
SET 
  `ENABLED` = "YES", 
  `TIMED` = "YES"
WHERE `NAME` LIKE "%statement/%";
```

```{sql setup-instruments-stage, echo = FALSE, eval = FALSE}
-- Disabled
UPDATE `performance_schema`.`setup_instruments` 
SET 
  `ENABLED` = "YES", 
  `TIMED` = "YES"
WHERE `NAME` LIKE "%stage/%";
```

```{sql setup-consumers-events-statements, echo = FALSE, eval = FALSE}
-- Disabled
UPDATE `performance_schema`.`setup_consumers` 
SET `ENABLED` = "YES"
WHERE `NAME` LIKE "%events_statements_%";
```

```{sql setup-consumers-events-stages, echo = FALSE, eval = FALSE}
-- Disabled
UPDATE `performance_schema`.`setup_consumers` 
SET `ENABLED` = "YES"
WHERE `NAME` LIKE "%events_stages_%";
```
