---
title: Drafts and Super Bowl Quarterbacks
description: The Quick Red Fox Jumps Over The Lazy Brown Dog. The Quick Red Fox Jumps Over The Lazy Brown Dog. 
post_type: post
categories: Sports, Football
mt_keywords: football, super bowl
wp_slug: drafted-super-bowl-quarterbacks
wp_author_display_name: timtrice
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    fig.align = "center",
    fig.height=5, 
    fig.width=10
)
```


```{r, include = FALSE}
library(ggplot2)
library(data.table)
library(xtable)
```

```{r, include = FALSE}
draft_qb <- readRDS("../../data/sports/football/draft_qb.rds")
sbqb <- readRDS("../../data/sports/football/sbqb.rds")
```

## Super Bowl Quarterbacks

I have two datasets that I parsed from [Pro-Football-Reference.com](http://www.pro-football-reference.com/). The first is of starting quarterbacks in a Super Bowl. The second is of all quarterback drafts since 1937. 

Here is a quick look at the data structures of both.

```{r}
str(draft_qb)

str(sbqb)
```


Here is a list of Super Bowl starting quarterbacks:

```{r, echo = FALSE, results = "asis"}
#print(xtable(sbqb[, .(Name, 
#                      Record = paste(AdjWins, "-", AdjLosses))][]), 
#      type = "html", 
#      include.rownames = FALSE)
```
