---
# General format taken from <https://dev.to/yelluw/how-to-do-technical-blogging>

# Title
#   - Short title, start with verb, provide brief explanation what this is about.
#   - Examples:
#     - Writing a $technology $thing
#     - Developing with $technology
#     - Testing $techonology with $thing
title: HURDAT v0.2.0

# Summary
#   - 2-3 sentences. 
#   - Summarize what post is about.
#   - Should be closely related to title
#   - Should be smooth transition from title
summary: > 
  HURDAT v0.2.0 has recently been released in CRAN. The new release contains all 
  tropical cyclones for the 2017 season, Atlantic and east Pacific basins. 

# Description is not used at this time but may be implemented later.
description: NULL

# Abstract is not used at this time but may be implemented later.
abstract: NULL

author: Tim Trice
date: '2018-06-08'

# Slug
#   - Use title without conjunctions and determiners.
#   - All lower-case.
# slug: hurdat-v0.2.0

# Categories
#   - General classification of post.
#     - SQL
#     - R
#     - Python
categories:
  - R

# Tags
#   - Calls specific to category such as functions, or classes.
#     - In SQL, "SELECT", "ORDER BY", "PARTITION", etc.
#     - In R, "dplyr", "rattle", "vector", etc."
tags:
  - HURDAT

output:
    blogdown::html_page:
        toc: true
        toc_depth: 6
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE)
```

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set()
```

```{r libraries}
library(ggridges)
library(HURDAT)
library(lubridate)
library(tidyverse)
```

```{r}
df <- union(AL, EP) %>% 
  mutate(Basin = case_when(
    str_sub(Key, 0L, 2L) == "AL" ~ "Atlantic", 
    str_sub(Key, 0L, 2L) == "EP" ~ "East Pacific", 
    str_sub(Key, 0L, 2L) == "CP" ~ "Central Pacific"))
```

```{r}
df %>% 
  group_by(Basin, 
           Year = year(DateTime)) %>% 
  summarise(Storms = n_distinct(Key)) %>% 
  mutate(Decade = paste0(10 * floor(Year/10), "'s")) %>% 
  ggplot(aes(x = Year, y = Storms, fill = Decade, color = Decade)) + 
  geom_ribbon(aes(ymin = 0, ymax = Storms), alpha = 0.35, color = NA) + 
  geom_line(size = 0.5) + 
  facet_wrap(~Basin, ncol = 1) + 
  scale_x_continuous(limits = c(1851, 2018), 
                     breaks = seq(1850, 2020, by = 20), 
                     minor_breaks = seq(1850, 2020, by = 10), 
                     expand = c(0, 0)) + 
  scale_y_continuous(limits = c(0, 35), 
                     expand = c(0, 0)) + 
  theme_bw() + 
  theme(legend.position = "none", 
        plot.subtitle = element_text(face = "italic", size = 10),
        strip.text = element_text(size = 10, color = "black", face = "bold", hjust = 1), 
        strip.background = element_rect(fill = "#FFFFFF")) + 
  labs(title = "Tropical cyclones by decade", 
       subtitle = "Introduction of weather satellites in 1960's", 
       caption = sprintf("@timtrice, HURDAT %s", packageVersion("HURDAT")))
```

```{r}
df %>% 
  mutate(Month = factor(month(DateTime, label = TRUE))) %>% 
  ggplot(aes(x = Wind, y = Month)) + 
  geom_density_ridges_gradient(aes(fill = ..x..), 
                               alpha = 0.85, 
                               scale = 0.85, 
                               rel_min_height = 0.01, 
                               size = 0.1) + 
  facet_wrap(~Basin, ncol = 1) + 
  coord_flip() +
  scale_y_discrete(expand = c(0, 0)) + 
  scale_fill_gradientn(colors = terrain.colors(10), name = "Wind Speed (kts)") + 
  theme_bw() + 
  theme(legend.position = "bottom", 
        plot.subtitle = element_text(face = "italic", size = 10),
        axis.text.x = element_text(hjust = -0.75), 
        axis.ticks.x = element_blank(), 
        strip.text = element_text(size = 10, color = "black", face = "bold", hjust = 1), 
        strip.background = element_rect(fill = "#FFFFFF")) + 
  labs(title = "Wind Observations by Month", 
       subtitle = "No known cyclones for Central Pacific from April through June.", 
       caption = sprintf("@timtrice, HURDAT %s", packageVersion("HURDAT")), 
       x = "Wind (kts)", 
       y = "")
```

## Average Speed of Tropical Cyclones over Time

```{r}
# @source: http://www.ridgesolutions.ie/index.php/2013/11/14/algorithm-to-calculate-speed-from-two-gps-latitude-and-longitude-points-and-time-difference/
distance <- function(lat1, lon1, lat2, lon2) {

	# Convert degrees to radians
	lat1 = lat1 * pi / 180.0
	lon1 = lon1 * pi / 180.0
 
	lat2 = lat2 * pi / 180.0
	lon2 = lon2 * pi / 180.0
 
	# radius of earth in metres
	r = 6378100;
 
	# P
	rho1 = r * cos(lat1)
	z1 = r * sin(lat1)
	x1 = rho1 * cos(lon1)
	y1 = rho1 * sin(lon1)
 
	# Q
	rho2 = r * cos(lat2)
	z2 = r * sin(lat2)
	x2 = rho2 * cos(lon2)
	y2 = rho2 * sin(lon2)
 
	# Dot product
	dot = (x1 * x2 + y1 * y2 + z1 * z2)
	cos_theta = dot / (r * r)
 
	theta = acos(cos_theta)
 
	# Distance in Metres
	return(r * theta)
}

# meters to miles
m_to_miles <- function(x) {
  return(x * 3.281 / 5280)
}
```

```{r}
df %>% 
  arrange(Key, DateTime) %>% 
  group_by(Key) %>% 
  summarise(Span = (last(DateTime) - first(DateTime))) %>% 
  filter(Span >= 1) %>% 
  left_join(df, by = "Key") %>% 
  group_by(Key, Year = year(DateTime)) %>% 
  mutate(Distance = distance(Lat, Lon, lag(Lat), lag(Lon)), 
         TimeDiff = as.integer(abs(DateTime - lag(DateTime))), 
         MPH = m_to_miles(Distance/TimeDiff)) %>% 
  summarise(AvgSpeed = mean(MPH, na.rm = TRUE)) %>% 
  ggplot(aes(x = Year, y = AvgSpeed)) + 
  geom_point() + 
  theme_bw() + 
  labs(title = "Average Forward Speed of Storms (MPH)", 
       subtitle = "Storms that have survived a minimum of 24 hours.", 
       caption = sprintf("@timtrice, HURDAT %s", packageVersion("HURDAT")))
```

```{r}

```

