---
title: Exploring HURDAT
summary: >
  Test description
author: 'Tim Trice'
date: '2017-05-15'
categories:
  - R
  - HURDAT
tags: 
  - analysis
draft: TRUE
output:
  blogdown::html_page:
    toc: true
    fig_align: center
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(fig.width = 10)
```

```{r libraries}
library(HURDAT)
library(tidyverse)
```

```{r data}
data(AL)
data(EP)
```

```{r}
AL %>% 
    mutate(Month = month(StartDate)) %>%
    group_by(Month) %>% 
    summarise(Count = n()) %>% 
    ggplot(aes(x = Month, y = Count, label = Count)) + 
    geom_point() + 
    geom_line() + 
    geom_label(vjust = -0.25) + 
    ylim(0, 625) + 
    scale_x_discrete(labels = c(month.abb), 
                     limits = c(1:12), 
                     expand = c(0.05, 0.05))
```

```{r}
EP_summary %>% 
    mutate(Month = month(StartDate)) %>%
    group_by(Month) %>% 
    summarise(Count = n()) %>% 
    ggplot(aes(x = Month, y = Count, label = Count)) + 
    geom_point() + 
    geom_line() + 
    geom_label(vjust = -0.25) + 
    ylim(0, 625) + 
    scale_x_discrete(labels = c(month.abb), 
                     limits = c(1:12), 
                     expand = c(0.05, 0.05))
```

```{r}
AL_summary %>% 
    ggplot(aes(x = MaxWind)) + 
    geom_histogram(binwidth=2)

EP_summary %>% 
    ggplot(aes(x = MaxWind)) + 
    geom_histogram(binwidth=2)
```

```{r}
AL_summary %>% 
    ggplot(aes(x = MaxWind, y = MinPressure)) + 
    geom_point() + 
    geom_smooth(method = "loess")

EP_summary %>% 
    ggplot(aes(x = MaxWind, y = MinPressure)) + 
    geom_point() + 
    geom_smooth(method = "loess")
```

