---
title: SQL Template
description: >
  Test description
subtitle: > 
  Test subtitle
abstract: > 
  Test abstract
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      error = TRUE, 
                      max.print = NA, 
                      connection = "mariadb_con")
```

```{r libraries, include = FALSE}
library(DBI)
library(knitr)
library(RMariaDB)
```

```{r db-con_params, include = FALSE}
mariadb.host <- Sys.getenv("mariadb.host")
mariadb.user <- Sys.getenv("mariadb.user")
mariadb.password <- Sys.getenv("mariadb.password")
```

```{r db-con, include = FALSE}
mariadb_con <- dbConnect(RMariaDB::MariaDB(), 
                 host = mariadb.host,
                 user = mariadb.user, 
                 password = mariadb.password)
```

### Content

### MariaDB Server Info

```{sql mariadb-version, connection = mariadb_con, tab.cap = "MariaDB Server Info"}
SELECT @@version_comment AS `Version`, 
  @@version_compile_machine AS `Version Compile Machine`, 
  @@innodb_version AS `InnoDB Version`, 
  @@version_compile_os AS `Version Compile OS`;
```

```{r close-mariadb, include = FALSE}
# Disconnect MariaDB
dbDisconnect(mariadb_con)
```
